server:
  port: 9990

eureka:
  client:
    serviceUrl:
      defaultZone: "http://127.0.0.1:8761/eureka/"
  instance:
    hostname: "127.0.0.1"
    leaseRenewalIntervalInSeconds: 10

spring:
  datasource:
    url: jdbc:mysql://47.105.82.42:3306/my?zeroDateTimeBehavior=round&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.105.82.42
    # Redis服务器连接端口
    port: 6379
  #     Redis服务器连接密码（默认为空）
  #    password: 123456
  application:
    name: my-admin


mybatis:
  mapperLocations: classpath:mapper/*.xml

# log level
logging:
  level: