server:
  port: 8766

spring:
  application:
    name: cib-scheduler-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: "jdbc:mysql://192.168.43.61:3306/cib?useSSL=false"
    username: icbc
    password: icbc

reg-center:
  server-list: "192.168.43.61:2181"
  namespace: elastic-job-lite-spring-boot

monitor:
  cron: 0/20 * * * * ?
  sharding-total-count: 2
  sharding-item-parameters: 0=CIB,1=ICBC
  job-description: "elastic simple job"
  job-parameter: "hello elastic simple job"

scriptJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=CIB,1=ICBC
  jobDescription: "elastic script job"
  jobParameter: "hello elastic script job"
  jobName: "elastic script job name"
  scriptCommandLine: "d:/run.bat"
