################### DataSource Configuration ##########################
server:
  port: 9901
spring:
  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.61:3306/cib?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: icbc
    password: icbc
  jpa:
    generate-ddl: false
    show-sql: true
    auto-ddl: update
    open-in-view: false
init-db: false

endpoints:
  health:
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true

management:
  security:
    enabled: false
  context-path: '/admin'
  port: 9902

datasource-reader:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.43.61:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: icbc
    password: icbc
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    sql-script-encoding: UTF-8

datasource-writer:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.43.61:3306/hdfs?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: icbc
    password: icbc
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    sql-script-encoding: UTF-8


hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create-drop
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: true
  format_sql: true

logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN